user_stories = [{"id": 0,
                 "title": "Test Title 1",
                 "story": "User Story Number One",
                 "criteria": "This works",
                 "business": 1000,
                 "estimation": 4,
                 "status": "TODO"},
                {"id": 1,
                 "title": "Test Title 2",
                 "story": "User Story Number Two",
                 "criteria": "This works too",
                 "business": 5000,
                 "estimation": 3,
                 "status": "DONE"}
                ]
